[build]
    functions = "functions"

[[redirects]]
    to = "/.netlify/functions/api/:splat"
    from = "/*"
    status = 200

# index.html uchun asosiy yo'lni belgilash
[[redirects]]
    from = "/*"
    to = "./disk/index.html"
    status = 200